### ISSUE TITLE
Migrate CI/CD processes to GitHub actions

### ISSUE THREAD

**Issue by tdudgeon** [xchem/xchem_it#16]
The Travis license expires in April (?) so we must switch over to using GitHub actions before then.

**Comment by reskyner** [comment]
Final deadline: 21st May

**Comment by alanbchristie** [comment]
The main repos have now been done and documented, along with a guide specifically for f/e dev: -

- fragalysis
- fragalysis-stack
- fragaysis-frontend
- fragalysis-backend
- fragalysis-api
- fragalysis-loader

We have omitted: -

- the slack notifications for now - based on a discussion of whether we want them and what we want them to do

> Note: The `fragalysis-pai` is suffereing form build errors but nothing that appears to be due to the migration, instead it may just be an upstream dependency issue.

**Comment by tdudgeon** [comment]
All have been migrated to github actions.
